import { test } from '@umbraco/playwright-testhelpers';
import dotenv from 'dotenv';

import { expect, prepareForScreenshot, screenshotOptions } from '../_helpers';
import { readSpellDeck } from '../_spellDeckFixture';
import { freshToken } from '../_umbracoApi';

dotenv.config();

// ---------------------------------------------------------------------------
// Screenshot: the Spellbook page (Step 10 of _work/spell-cards/plan.md).
//
// THREE CAPTURES, ALL AT REAL CARD COUNTS. Sample-size content is precisely
// what hid the scale problem in the deck's first design round — four cards look
// fine in any layout — so every baseline here is taken against the shipped
// roster, sixteen-card Core panel included.
//
//   1. the resting stack row, every stack closed   (the deck's front door)
//   2. the Core stack open                          (the dense case)
//   3. the Core stack open at phone width           (the carousel layout)
//
// HOW "EVERY STACK CLOSED" IS REACHED. The server renders the block's
// `deckDefaultStack` open, so the closed state is not a URL the server can
// serve — it is what the deck writes to the fragment when the visitor closes a
// stack. Loading a bare `#deck` restores exactly that state through the same
// code path, with no clicking and no waiting on an animation to finish.
//
// THE HEADER IS IN ALL THREE, AND IT IS A 60-MINUTE CACHED PARTIAL
// (`master.cshtml:34` wraps `_SiteHead.cshtml` in `Html.CachedPartialAsync`).
// A baseline taken against a warm cache can bake in a nav that predates the
// Spellbook page — and since baselines are generated on CI against Dev, that is
// a stale-content bug nobody would think to look for in an image diff. So the
// nav link is ASSERTED, not eyeballed: if the cached header has not caught up,
// this spec fails with a sentence about the cache rather than producing a
// quietly wrong baseline.
//
// BASELINES ARE LINUX-ONLY. They are generated by the `update-snapshots.yml`
// workflow; `*-darwin.png` is gitignored and this spec is EXPECTED to fail on a
// developer Mac until CI has produced them. Never run this spec with
// `--update-snapshots` locally, and never regenerate a baseline to make a diff
// pass.
// ---------------------------------------------------------------------------

let spellbookPath: string;

test.beforeAll(async () => {
  // Fail fast with a clear auth error rather than a puzzling tree-walk failure.
  await freshToken();
  const deck = await readSpellDeck();
  spellbookPath = new URL(deck.spellbookUrl, 'https://localhost').pathname;
});

/** Navigate, confirm the header nav has caught up, and settle the page. */
async function openSpellbook(page: import('@playwright/test').Page, hash = '') {
  const resp = await page.goto(`${spellbookPath}${hash}`);
  expect(resp?.ok(), `navigation to ${spellbookPath}${hash} should succeed`).toBeTruthy();

  const navLink = page.locator(
    `header a[href="${spellbookPath}"], header a[href="${spellbookPath.replace(/\/$/, '')}"]`
  );
  await expect(
    navLink,
    'the header nav should link to the Spellbook page — if it does not, the 60-minute ' +
      'CachedPartialAsync header is stale and any baseline taken now would bake that in. ' +
      'Restart the site (or wait out the cache) before generating baselines.'
  ).not.toHaveCount(0);

  await prepareForScreenshot(page);
}

test.describe('Screenshot: Spellbook page', () => {
  test('renders the resting stack row with every stack closed', async ({ page }) => {
    await page.setViewportSize({ width: 1280, height: 900 });
    await openSpellbook(page, '#deck');

    await expect(
      page.locator('.spell-deck__panel:not([hidden])'),
      'a bare #deck closes every panel'
    ).toHaveCount(0);

    await expect(page).toHaveScreenshot(
      'spellbook-stacks-closed.png',
      screenshotOptions({
        fullPage: true,
        mask: [page.locator('time, .post-meta, .article-meta')],
      })
    );
  });

  test('renders the Core stack open', async ({ page }) => {
    await page.setViewportSize({ width: 1280, height: 900 });
    await openSpellbook(page);

    await expect(
      page.locator('.spell-deck__panel:not([hidden])'),
      'exactly one panel is open on arrival'
    ).toHaveCount(1);

    await expect(page).toHaveScreenshot(
      'spellbook-core-open.png',
      screenshotOptions({
        fullPage: true,
        mask: [page.locator('time, .post-meta, .article-meta')],
      })
    );
  });

  test('renders the open stack at phone width', async ({ page }) => {
    // Below the stylesheet's single 700px breakpoint: the card rows become
    // scroll-snap carousels and the prev/next arrows appear.
    await page.setViewportSize({ width: 390, height: 844 });
    await openSpellbook(page);

    await expect(
      page.locator('.spell-deck__panel:not([hidden]) .spell-deck__carousel-nav').first(),
      'the carousel arrows are visible below 700px'
    ).toBeVisible();

    await expect(page).toHaveScreenshot(
      'spellbook-phone.png',
      screenshotOptions({
        fullPage: true,
        mask: [page.locator('time, .post-meta, .article-meta')],
      })
    );
  });
});
